# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
    - name: Install Dependencies
      run: npm install
    - name: Update Dependencies
      run: npm update
    - name: Commit Changes
      run: |
        git config --global user.email "net4hhhh@163.com"
        git config --global user.name "Cccc-owo"
        git add -A
        git commit -m "Update dependencies by GitHub Actions"
    - name: GitHub Push
  # You may pin to the exact commit or the version.
  # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
       # Token for the repo. Can be passed in using ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
       # Destination branch to push changes
        branch: main # optional, default is master
       # Determines if force push is used
       # force: # optional
